services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memorandum
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:80"
    networks:
      - documentation
    deploy:
      resources:
        limits:
          memory: 512m

# docker network create documentation
networks:
  documentation:
    name: documentation
    external: true
