// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppImg: typeof import('./components/app/img.vue')['default']
    AppTab: typeof import('./components/app/tab.vue')['default']
    AppTabs: typeof import('./components/app/tabs.vue')['default']
    ContentCodeBlock: typeof import('./components/content/code-block.vue')['default']
    ContentCodeGroup: typeof import('./components/content/code-group.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svg-icon.vue')['default']
    Theme: typeof import('./components/theme/index.vue')['default']
    ThemeContent: typeof import('./components/theme/content.vue')['default']
    ThemeDirectoryList: typeof import('./components/theme/directory-list.vue')['default']
    ThemeSidebar: typeof import('./components/theme/sidebar.vue')['default']
    ThemeSidebarStatic: typeof import('./components/theme/sidebar-static.vue')['default']
  }
}

export {}
